require("config.packer")
require("config.sets")
require("config.keymap")
require("config.autocommands")
require("config.telescope")
require("config.miniindent")
-- require("config.blankline")
require("config.neogit")
require("config.cursorline")
require("config.tabnine")

