border_width = 2
margin = [4, 8, 4, 8]
# default_border_color = "#5e81ac"
default_border_color = "#3b5261"
# focused_border_color = "#a3be8c"
focused_border_color = "#3b4261"
# floating_border_color = "#88c0d0"
floating_border_color = "#7aa2f7"
